#!/bin/bash

IMAGEDIR="$1"
wifi_img="$2"
interface="$3"

NETWORK=$(netctl list | sed -n 's/^\* //p')
if [[ -z "$NETWORK" ]]; then
  NETWORK="$(wpa_cli -i "$interface" status | sed -n 's/^id_str=//p')"
fi
DOWNARROW="^i($IMAGEDIR/downarrow.xpm,7)"
UPARROW="^i($IMAGEDIR/uparrow.xpm,7)"

if [ -f "/etc/netctl/$NETWORK" ]
then
    CONNTYPE=$(< "/etc/netctl/$NETWORK" grep -iE "^CONNECTION" \
        | sed -e "s/.*=['\"]\?\([^'\"]\+\)['\"]\?/\1/")
    INTERFACE=$(< "/etc/netctl/$NETWORK" grep -iE "^INTERFACE" \
        | sed -e "s/.*=['\"]\?\([^'\"]\+\)['\"]\?/\1/")

    case "$CONNTYPE" in
        wireless)
            echo "text net1 \
$DOWNARROW\\#\${downspeedf $INTERFACE}\\#kB/s|\
$UPARROW\\#\${upspeedf $INTERFACE}\\#kB/s
text net2 \
$NETWORK|\
\${addrs $INTERFACE}
text net3 \
^i($IMAGEDIR/$(exec $wifi_img $INTERFACE),10)\\#\
\${wireless_link_qual_perc $INTERFACE}%|\
\${wireless_essid $INTERFACE}\
"
            ;;
        ethernet)
            echo "text net1 \
$DOWNARROW\\#\${downspeed $INTERFACE} kB/s|\
$UPARROW\\#\${upspeed $INTERFACE} kB/s
text net2 \
$NETWORK|\
\${addrs $INTERFACE}\
"
            ;;
        *)
            echo "CONNTYPE: $CONNTYPE|INTERFACE: $INTERFACE"
            ;;
    esac
fi

echo

exit 0
