#!/bin/bash
#
# Check the volume and return the correct image
#

volimg() {
  if (amixer sget Master | grep -qF [off])
  then
    echo -n snd-m.xpm
  else
    p=$(amixer sget Master | grep -oe '[0-9]\+%' | head -1 )
    p=${p%\%}
    if [ "$p" -lt "15" ]; then 
      echo -n snd-0.xpm
    elif [ "$p" -lt "50" ]; then 
      echo -n snd-1.xpm
    elif [ "$p" -lt "85" ]; then 
      echo -n snd-2.xpm
    else
      echo -n snd-3.xpm
    fi
  fi
}
  
VOLUME_CA_START="^ca(1, amixer sset Master toggle -q)^ca(4, amixer sset Master 3%+ -q)^ca(5, amixer sset Master 3%- -q)"
VOLUME_CA_END="^ca()^ca()^ca()"
IMAGEDIR="$1"

true
while [ $? -ne 1 -a $? -ge 0 ]
do
  icon=$IMAGEDIR/$(volimg)
  echo "text volume $VOLUME_CA_START^i($icon,12)$VOLUME_CA_END#"
  inotifywait -t 30 /dev/snd/controlC0 -qq
done
