#!/bin/bash
#
# Set up the status bars
#

function _shutdown() {
  rm -f $SOCKET
  pkill -TERM -P $$
}

trap _shutdown INT TERM QUIT

DEBUG=no

BASEDIR="$(cd "$(dirname ${BASH_SOURCE[0]})" && pwd)"
IMAGEDIR="$BASEDIR/images"
SCRIPTDIR="$BASEDIR"

echo "BASEDIR: $BASEDIR"

wifi_img="$SCRIPTDIR/wifi"
bat_img="$SCRIPTDIR/battery"
bat_time="$SCRIPTDIR/battery-time"

SOCKET=$BASEDIR/dzen.socket

write() {
  echo "$@" | ncat -U $SOCKET
}

run() {
  if [[ "$DEBUG" == "yes" ]]; then
    echo "run: ${@:2} | tee $BASEDIR/${1}.log | ncat -U $SOCKET"
    "${@:2}" | tee $BASEDIR/${1}.log | ncat -U $SOCKET
  else
    "${@:2}" | ncat -U $SOCKET
  fi
}

if ! hash dzcoord &> /dev/null; then
  echo "dzcoord not available, aborting..." >&2
  exit 1
fi

# Start the bar program
rm -f $SOCKET
if [[ "$DEBUG" == "yes" ]]; then
  ncat -Ulk $SOCKET | tee $BASEDIR/input.log | dzcoord 2> $BASEDIR/bar.log &
else
  ncat -Ulk $SOCKET | dzcoord 2> $BASEDIR/bar.log &
fi

sleep 0.1

UPRIGHT="text info \
^i($IMAGEDIR/cpu.xpm,12)#\$cpu% \$freq_g GHz|\
^i($IMAGEDIR/ram.xpm,12)#\$memperc%|\${exec $bat_img}#\${battery_percent BAT1}% \
\${exec $bat_time}^norm()|\
\${time %a %Y-%m-%d %H:%M:%S}#"
write "add_area info 0 TOP 1000 RIGHT"
sleep 0.1
run "upright" conky -u 1 -t "$UPRIGHT" &

NETTXT="\${execp $SCRIPTDIR/network}"
write "add_area net 0 BOTTOM 100 LEFT"
sleep 0.1
run "nettxt" conky -u 1 -t "text net $NETTXT" 2> /dev/null &



write "add_area volume 0 BOTTOM 100 RIGHT"
sleep 0.1
bat() {
  VOLUME_CA_START="^ca(1, amixer sset Master toggle -q)^ca(4, amixer sset Master 3%+ -q)^ca(5, amixer sset Master 3%- -q)"
  VOLUME_CA_END="^ca()^ca()^ca()"
  true
  while [ $? -ne 1 -a $? -ge 0 ]
  do
    icon=$IMAGEDIR/$($SCRIPTDIR/volume)
    echo "text volume $VOLUME_CA_START^i($icon,12)$VOLUME_CA_END#"
    inotifywait -t 30 /dev/snd/controlC0 -qq
  done
}
run "bat" bat &

write "add_area servers 0 BOTTOM 90 RIGHT"
sleep 0.1
servers() {
  true
  while [ $? -eq 0 ]
  do
    $SCRIPTDIR/servers.sh
    sleep 60
  done
}
run "servers" servers

echo "Ending load statusbars"

write "\
rm_area xmonad
rm_area info
rm_area net
rm_area volume"
